name: Run-integration-tests

on:
  pull_request:
    branches: [master]

jobs:
  integration-tests-3-7:
    name: Run integration tests for 3.7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install requirements.txt
        run: >-
          python -m 
          pip install -r requirements.txt
      - name: Install requirements.test.txt
        run: >-
          python -m 
          pip install -r requirements.test.txt
      - name: Run integration tests
        run: >-
          python -m pytest tests/integrationtests/test_commands
  integration-tests-3-8:
    name: Run integration tests for 3.8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install requirements.txt
        run: >-
          python -m 
          pip install -r requirements.txt
      - name: Install requirements.test.txt
        run: >-
          python -m 
          pip install -r requirements.test.txt
      - name: Run integration tests
        run: >-
          python -m pytest tests/integrationtests/test_commands
  integration-tests-3-9:
    name: Run integration tests for 3.9
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install requirements.txt
        run: >-
          python -m 
          pip install -r requirements.txt
      - name: Install requirements.test.txt
        run: >-
          python -m 
          pip install -r requirements.test.txt
      - name: Run integration tests
        run: >-
          python -m pytest tests/integrationtests/test_commands
  integration-tests-3-10:
    name: Run integration tests for 3.10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.14
      - name: Install requirements.txt
        run: >-
          python -m 
          pip install -r requirements.txt
      - name: Install requirements.test.txt
        run: >-
          python -m 
          pip install -r requirements.test.3.7.txt
      - name: Run integration tests
        run: >-
          python -m pytest tests/integrationtests/test_commands
  integration-tests-3-11:
    name: Run integration tests for 3.11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Install requirements.txt
        run: >-
          python -m 
          pip install -r requirements.txt
      - name: Install requirements.test.txt
        run: >-
          python -m 
          pip install -r requirements.test.txt
      - name: Run integration tests
        run: >-
          python -m pytest tests/integrationtests/test_commands
  integration-tests-3-12:
    name: Run integration tests for 3.12
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.12
      - name: Install requirements.txt
        run: >-
          python -m 
          pip install -r requirements.txt
      - name: Install requirements.test.txt
        run: >-
          python -m 
          pip install -r requirements.test.txt
      - name: Run integration tests
        run: >-
          python -m pytest tests/integrationtests/test_commands
